actor:
  _target_: src.networks.actor_critic.GaussianActor
  hidden_dims: [64, 64]
  activation:
    _target_: hydra.utils.get_method
    path: flax.linen.tanh # src.networks.activation.mish  # flax.linen.relu
  log_std_min: -5
  log_std_max: 2
critic:
  _target_: src.networks.actor_critic.ValueCritic
  hidden_dims: [64, 64]
  activation:
    _target_: hydra.utils.get_method
    path: flax.linen.tanh # src.networks.activation.mish  #flax.linen.relu
